### ISSUE TITLE
Missing bottom and right corners

### ISSUE THREAD

**Issue by sylveon** [Obsidian-StudiosInc/eminence#1]
I don't know of this is really visible, but bottom and right corners are missing in the "context menu" of terminology

![image](https://user-images.githubusercontent.com/6440374/29498314-3476a48e-85c7-11e7-8497-1735afa48a58.png)
Same happens with settings
![image](https://user-images.githubusercontent.com/6440374/29498315-3ef40cee-85c7-11e7-9f43-031322dc8411.png)

**Comment by wltjr** [comment]
Yes if you mean the bottom right corner is square/right angle vs rounded border. Seems the other 3 are rounded as they should be, but not that bottom right corner. Assuming that is what you mean :)

**Comment by sylveon** [comment]
That is part of it, yes. But if you look more closely you can see a black
outline on top and left of the form. There isn't on bottom and right.

**Comment by wltjr** [comment]
Ok thanks, something is likely off with the bottom on those objects. I will take a look and address ASAP. Thank you for the report and details!

**Comment by sylveon** [comment]
Fixed by a terminology update

**Comment by wltjr** [comment]
That's good, I was looking into that and not having much luck. That explains why :)
